packages: []
allowBuilds:
  esbuild: false
  mongodb-memory-server: false
  msgpackr-extract: false
  protobufjs: false
  workerd: false
minimumReleaseAgeExclude:
  - "@electric-sql/pglite@0.5.5"
  - miniflare@5.20260811.1-alpha
  - wrangler@4.123.0
