// Generated by nuxt-site-config

declare module 'nitropack' {
  interface NitroRouteRules {
    site?: import('../../node_modules/.pnpm/nuxt-site-config@1.6.7_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.10_nuxt@3.9.1_postcss@8.4._ck4efiyoe4jhtk6pzlq4kpsodq/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigInput
  }
  interface NitroRouteConfig {
    site?: import('../../node_modules/.pnpm/nuxt-site-config@1.6.7_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.10_nuxt@3.9.1_postcss@8.4._ck4efiyoe4jhtk6pzlq4kpsodq/node_modules/nuxt-site-config/dist/runtime/types').SiteConfig
  }
}

declare module 'h3' {
  interface H3EventContext {
    siteConfig: import('../../node_modules/.pnpm/nuxt-site-config@1.6.7_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.10_nuxt@3.9.1_postcss@8.4._ck4efiyoe4jhtk6pzlq4kpsodq/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigStack
  }
}

declare module 'nuxt/schema' {
  interface AppConfigInput {
    /** Theme configuration */
    site?: import('../../node_modules/.pnpm/nuxt-site-config@1.6.7_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.10_nuxt@3.9.1_postcss@8.4._ck4efiyoe4jhtk6pzlq4kpsodq/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigInput
  }
}

declare module '@nuxt/schema' {
  interface AppConfigInput {
    /** Theme configuration */
    site?: import('../../node_modules/.pnpm/nuxt-site-config@1.6.7_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.10_nuxt@3.9.1_postcss@8.4._ck4efiyoe4jhtk6pzlq4kpsodq/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigInput
  }
  interface Nuxt {
    _siteConfig?: import('../../node_modules/.pnpm/nuxt-site-config@1.6.7_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.10_nuxt@3.9.1_postcss@8.4._ck4efiyoe4jhtk6pzlq4kpsodq/node_modules/nuxt-site-config/dist/runtime/types').SiteConfigStack
  }
}

declare module '@nuxt/schema' {
  export interface RuntimeNuxtHooks {
    'site-config:resolve': (siteConfig: import('../../node_modules/.pnpm/nuxt-site-config@1.6.7_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.10_nuxt@3.9.1_postcss@8.4._ck4efiyoe4jhtk6pzlq4kpsodq/node_modules/nuxt-site-config/dist/runtime/types').SiteConfig) => void
  }
}

export {}
