// Generated by nuxt-og-image

declare module 'nitropack' {
  interface NitroRouteRules {
    ogImage?: false | import('../../node_modules/.pnpm/nuxt-og-image@2.2.4_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.10_nuxt@3.9.1_postcss@8.4.33__rv5seja7eaudj7eewivm5fnaii/node_modules/nuxt-og-image/dist/runtime/types').OgImageOptions
  }
  interface NitroRouteConfig {
    ogImage?: false | import('../../node_modules/.pnpm/nuxt-og-image@2.2.4_@nuxt+devtools@1.0.8_@vue+compiler-core@3.4.10_nuxt@3.9.1_postcss@8.4.33__rv5seja7eaudj7eewivm5fnaii/node_modules/nuxt-og-image/dist/runtime/types').OgImageOptions
  }
}
export {}
