// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "/Users/atinux/Projects/unjs/unstorage/docs/app.config";
import type { default as appConfig1 } from "/Users/atinux/Projects/unjs/unstorage/docs/_theme/app.config";
import type { default as appConfig2 } from "/Users/atinux/Projects/unjs/unstorage/docs/node_modules/.pnpm/@nuxt+ui-pro@0.7.0_nuxt@3.9.1_vite@5.0.11_vue@3.3.13/node_modules/@nuxt/ui-pro/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1, typeof appConfig2]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}