packages: []
allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  vue-demi: false
ignoredBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - vue-demi
onlyBuiltDependencies:
  - better-sqlite3
