name: autofix.ci
on: { push: {}, pull_request: {} }
permissions: { contents: read }
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with: { node-version: lts/*, cache: pnpm }
      - run: pnpm install
      - run: pnpm fmt
      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8
        with: { commit-message: "chore: apply automated updates" }
